name: Sync Fork

on:
  push:
    # delete this item if you don't want to trigger this workflow when modify this repo
    branches: main
  
  schedule:
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 18 * * *'
    # - cron: '*/60 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: Meroser
          base: main
          head: main
